import type { AuthModelInfo } from './ast-transform'
import type { ParamDef, ShapeFilterDef } from './types'

/**
 * Generate the TypeScript source code for the electric-filters.ts file.
 */
export function generateFiltersSource(
  filters: Record<string, ShapeFilterDef | null>,
  authModel?: AuthModelInfo | null,
): string {
  const lines: string[] = [
    `// Generated by zenstack-electric — do not edit manually`,
    `import { resolveShapeFilter } from 'zenstack-electric'`,
    `import type { ShapeFilter, ShapeFilterDef, ParamDef } from 'zenstack-electric'`,
    ``,
  ]

  if (authModel) {
    lines.push(`export interface AuthModelType {`)
    for (const field of authModel.fields) {
      const opt = field.optional ? '?' : ''
      lines.push(`  ${field.name}${opt}: ${field.type}`)
    }
    lines.push(`}`)
    lines.push(``)
  }

  lines.push(`export const shapeFilterDefs: Record<string, ShapeFilterDef | null> = {`)

  for (const [modelName, def] of Object.entries(filters)) {
    if (def === null) {
      lines.push(`  ${modelName}: null,`)
    }
    else {
      lines.push(`  ${modelName}: {`)
      lines.push(`    where: ${JSON.stringify(def.where)},`)
      lines.push(`    params: [`)
      for (const param of def.params) {
        lines.push(`      ${serializeParamDef(param)},`)
      }
      lines.push(`    ],`)
      lines.push(`  },`)
    }
  }

  lines.push(`}`)
  lines.push(``)

  const authParamType = authModel ? 'Partial<AuthModelType>' : 'Record<string, any>'
  lines.push(`export function getShapeFilter(model: string, auth?: ${authParamType}): ShapeFilter | null {`)
  lines.push(`  const def = shapeFilterDefs[model]`)
  lines.push(`  if (def === undefined) throw new Error(\`Unknown model: \${model}\`)`)
  lines.push(`  return resolveShapeFilter(def, auth)`)
  lines.push(`}`)
  lines.push(``)

  return lines.join('\n')
}

function serializeParamDef(param: ParamDef): string {
  if (param.kind === 'static') {
    return `{ kind: 'static', value: ${JSON.stringify(param.value)} }`
  }
  return `{ kind: 'auth', path: ${JSON.stringify(param.path)} }`
}
